tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-dim": "#e1d8d4",
        "on-surface-variant": "#554241",
        "secondary-fixed": "#f2dfd3",
        "on-secondary-fixed-variant": "#51443b",
        "error-container": "#ffdad6",
        "inverse-surface": "#34302c",
        "surface-container-high": "#efe6e2",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#f5ece7",
        background: "#fff8f5",
        primary: "#390004",
        "secondary-fixed-dim": "#d5c3b7",
        surface: "#fff8f5",
        "on-tertiary-fixed": "#281801",
        "on-error": "#ffffff",
        "on-primary-container": "#de7470",
        "inverse-primary": "#ffb3af",
        secondary: "#695c52",
        "primary-fixed": "#ffdad7",
        outline: "#887270",
        "inverse-on-surface": "#f8efea",
        tertiary: "#241500",
        "surface-container-low": "#fbf2ed",
        error: "#ba1a1a",
        "on-tertiary-fixed-variant": "#584325",
        "surface-bright": "#fff8f5",
        "tertiary-fixed-dim": "#e0c29a",
        "surface-tint": "#9c413f",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#410005",
        "primary-fixed-dim": "#ffb3af",
        "on-tertiary-container": "#ab8f6b",
        "tertiary-fixed": "#feddb4",
        "tertiary-container": "#3b290d",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "surface-container-highest": "#e9e1dc",
        "on-background": "#1e1b18",
        "secondary-container": "#efdcd0",
        "on-secondary-fixed": "#231a12",
        "surface-variant": "#e9e1dc",
        "on-secondary-container": "#6e6056",
        "on-primary-fixed-variant": "#7d2a2a",
        "primary-container": "#590f12",
        "on-surface": "#1e1b18",
        "outline-variant": "#dbc0be",
        "on-tertiary": "#ffffff",
      },
      fontFamily: {
        headline: ["Noto Serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
    },
  },
};
